server:
  port: 8081

spring:
  application:
    name: rider-service
  datasource:
    url: jdbc:postgresql://localhost:5442/geofleet_rider
    username: geofleet
    password: geofleet
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: when_authorized
